-- idiomas
INSERT INTO idioma(nombre) VALUES ('FRANCÉS');
INSERT INTO idioma(nombre) VALUES ('ESPAÑOL');
INSERT INTO idioma(nombre) VALUES ('ALEMÁN');
INSERT INTO idioma(nombre) VALUES ('ITALIANO');
INSERT INTO idioma(nombre) VALUES ('PORTUGUÉS');
INSERT INTO idioma(nombre) VALUES ('RUSO');
INSERT INTO idioma(nombre) VALUES ('CHINO');
INSERT INTO idioma(nombre) VALUES ('JAPONÉS');
INSERT INTO idioma(nombre) VALUES ('ÁRABE');
INSERT INTO idioma(nombre) VALUES ('HINDI');
-- categorias
INSERT INTO categoria(nombre) VALUES ('FANTASÍA');
INSERT INTO categoria(nombre) VALUES ('TERROR');
INSERT INTO categoria(nombre) VALUES ('HISTORIA');
INSERT INTO categoria(nombre) VALUES ('ROMANCE');
INSERT INTO categoria(nombre) VALUES ('AVENTURA');
INSERT INTO categoria(nombre) VALUES ('MISTERIO');
INSERT INTO categoria(nombre) VALUES ('THRILLER PSICOLÓGICO');
INSERT INTO categoria(nombre) VALUES ('CIENCIA');
INSERT INTO categoria(nombre) VALUES ('FILOSOFÍA');
INSERT INTO categoria(nombre) VALUES ('AUTOAYUDA');
INSERT INTO categoria(nombre) VALUES ('EDUCACIÓN');
INSERT INTO categoria(nombre) VALUES ('BIOGRAFÍAS');
INSERT INTO categoria(nombre) VALUES ('DIARIOS');
INSERT INTO categoria(nombre) VALUES ('POESÍA');
INSERT INTO categoria(nombre) VALUES ('CUENTOS');
INSERT INTO categoria(nombre) VALUES ('DRAMA');
INSERT INTO categoria(nombre) VALUES ('INFANTIL');
INSERT INTO categoria(nombre) VALUES ('JUVENIL');
INSERT INTO categoria(nombre) VALUES ('GUIAS DE VIAJE');
INSERT INTO categoria(nombre) VALUES ('COCCIÓN');
-- autores
INSERT INTO autor(nombres, apellidos) VALUES ('MARK', 'TWAIN');
INSERT INTO autor(nombres, apellidos) VALUES ('JANE', 'AUSTEN');
INSERT INTO autor(nombres, apellidos) VALUES ('WILLIAM', 'SHAKESPEARE');
INSERT INTO autor(nombres, apellidos) VALUES ('CHARLES', 'DICKENS');
INSERT INTO autor(nombres, apellidos) VALUES ('VIRGINIA', 'WOOLF');
INSERT INTO autor(nombres, apellidos) VALUES ('GEORGE', 'ORWELL');
INSERT INTO autor(nombres, apellidos) VALUES ('J.K.', 'ROWLING');
INSERT INTO autor(nombres, apellidos) VALUES ('GABRIEL GARCÍA', 'MÁRQUEZ');
INSERT INTO autor(nombres, apellidos) VALUES ('LEO', 'TOLSTOY');
INSERT INTO autor(nombres, apellidos) VALUES ('FRIEDRICH', 'NIETZSCHE');
INSERT INTO autor(nombres, apellidos) VALUES ('HERMAN', 'MELVILLE');
INSERT INTO autor(nombres, apellidos) VALUES ('J.R.R.', 'TOLKIEN');
INSERT INTO autor(nombres, apellidos) VALUES ('ERNEST', 'HEMINGWAY');
INSERT INTO autor(nombres, apellidos) VALUES ('FRANZ', 'KAFKA');
INSERT INTO autor(nombres, apellidos) VALUES ('OSCAR', 'WILDE');
INSERT INTO autor(nombres, apellidos) VALUES ('FYODOR', 'DOSTOEVSKY');
INSERT INTO autor(nombres, apellidos) VALUES ('AGATHA', 'CHRISTIE');
INSERT INTO autor(nombres, apellidos) VALUES ('LOUISA MAY', 'ALCOTT');
INSERT INTO autor(nombres, apellidos) VALUES ('EDGAR ALLAN', 'POE');
INSERT INTO autor(nombres, apellidos) VALUES ('EMILY', 'DICKINSON');
-- libros
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1980, 1, '1122334455', '978-1122334455', 'epica_aventura_001.png', 'Un viaje lleno de misterios, magia y descubrimientos.', 'El Viaje del Héroe', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1995, 2, '2233445566', '978-2233445566', 'thriller_psicologico_002.png', 'Secretos oscuros y revelaciones impactantes en cada página.', 'Mentes Ocultas', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2005, 3, '3344556677', '978-3344556677', 'historia_amor_003.png', 'El poder del amor contra las adversidades del destino.', 'Amor Eterno', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2010, 4, '4455667788', '978-4455667788', 'ciencia_ficcion_004.png', 'Un futuro donde la tecnología cambia la esencia de la humanidad.', 'Horizontes Nuevos', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1950, 5, '5566778899', '978-5566778899', 'literatura_fantastica_005.png', 'Un mundo donde la magia es real y palpable.', 'Reinos de Fantasía', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1978, 6, '6677889900', '978-6677889900', 'relato_supervivencia_006.png', 'La lucha del espíritu humano frente a la naturaleza indómita.', 'Al Límite', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1989, 7, '7788990011', '978-7788990011', 'relaciones_familiares_007.png', 'Familia, secretos y el viaje hacia la redención.', 'Lazos Familiares', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2000, 8, '8899001122', '978-8899001122', 'misterio_antigua_mansion_008.png', 'Secretos del pasado y espíritus que no descansan.', 'Ecos del Pasado', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2016, 9, '9900112233', '978-9900112233', 'distopia_libertad_009.png', 'En un futuro oscuro, la búsqueda de la verdad es lo único que importa.', 'Última Esperanza', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2022, 10, '0011223344', '978-0011223344', 'viaje_selva_amazonica_010.png', 'Descubrimientos antiguos y peligros modernos en la selva.', 'Corazón de la Selva', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1990, 1, '1234567890', '978-1234567890', 'historias_piratas_011.png', 'Aventuras, tesoros escondidos y leyendas de los siete mares.', 'Mares Salvajes', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2008, 2, '2345678901', '978-2345678901', 'investigacion_criminal_012.png', 'Misterio y arte se entrelazan en una trama apasionante.', 'Sombras de Gaudí', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2014, 3,  '3456789012', '978-3456789012', 'biografia_revolucionario_013.png', 'La lucha, el poder y el sacrificio de un líder.', 'Voces de Libertad', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1972, 4, '4567890123', '978-4567890123', 'impacto_tecnologia_014.png', 'Reflexiones sobre el avance tecnológico y la ética.', 'Futuro Imperfecto', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1964, 5, '5678901234', '978-5678901234', 'guerra_civil_espanola_015.png', 'El horror, la esperanza y la lucha en tiempos de guerra.', 'Ecos de la Guerra', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2018, 6, '6789012345', '978-6789012345', 'saga_familiar_016.png', 'Amor, pérdida y redención en el siglo XX.', 'Raíces Profundas', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2021, 7, '7890123456', '978-7890123456', 'distopia_colapso_ambiental_017.png', 'La lucha por los recursos en un mundo al borde del abismo.', 'Último Aliento', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2019, 8, '8901234567', '978-8901234567', 'ensayo_cultura_pop_018.png', 'Cómo los medios moldean nuestra percepción del mundo.', 'Cultura en Píxeles', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (1986, 9, '9012345678', '978-9012345678', 'thriller_espionaje_019.png', 'Intriga y suspense en una carrera contra el tiempo.', 'Sombras Frías', TRUE);
INSERT INTO libro (anio_publicacion, idioma, isbn10, isbn13, portada, sinopsis, titulo, disponibilidad) VALUES (2002, 10, '0123456789', '978-0123456789', 'conquista_espacio_020.png', 'La aventura humana más allá de la Tierra.', 'Estrellas Distantes', TRUE);
-- autores libros
INSERT INTO autor_libro(libro, autor) VALUES (1, 5);
INSERT INTO autor_libro(libro, autor) VALUES (2, 14);
INSERT INTO autor_libro(libro, autor) VALUES (3, 7);
INSERT INTO autor_libro(libro, autor) VALUES (4, 2);
INSERT INTO autor_libro(libro, autor) VALUES (5, 18);
INSERT INTO autor_libro(libro, autor) VALUES (6, 11);
INSERT INTO autor_libro(libro, autor) VALUES (7, 4);
INSERT INTO autor_libro(libro, autor) VALUES (8, 16);
INSERT INTO autor_libro(libro, autor) VALUES (9, 9);
INSERT INTO autor_libro(libro, autor) VALUES (10, 20);
INSERT INTO autor_libro(libro, autor) VALUES (11, 3);
INSERT INTO autor_libro(libro, autor) VALUES (12, 8);
INSERT INTO autor_libro(libro, autor) VALUES (13, 6);
INSERT INTO autor_libro(libro, autor) VALUES (14, 10);
INSERT INTO autor_libro(libro, autor) VALUES (15, 13);
INSERT INTO autor_libro(libro, autor) VALUES (16, 17);
INSERT INTO autor_libro(libro, autor) VALUES (17, 1);
INSERT INTO autor_libro(libro, autor) VALUES (18, 12);
INSERT INTO autor_libro(libro, autor) VALUES (19, 15);
INSERT INTO autor_libro(libro, autor) VALUES (20, 19);
INSERT INTO autor_libro(libro, autor) VALUES (1, 10);
INSERT INTO autor_libro(libro, autor) VALUES (2, 3);
INSERT INTO autor_libro(libro, autor) VALUES (3, 13);
INSERT INTO autor_libro(libro, autor) VALUES (4, 7);
INSERT INTO autor_libro(libro, autor) VALUES (5, 2);
INSERT INTO autor_libro(libro, autor) VALUES (6, 8);
INSERT INTO autor_libro(libro, autor) VALUES (7, 14);
INSERT INTO autor_libro(libro, autor) VALUES (8, 1);
INSERT INTO autor_libro(libro, autor) VALUES (9, 6);
INSERT INTO autor_libro(libro, autor) VALUES (10, 4);
-- categorias libros
INSERT INTO categoria_libro(libro, categoria) VALUES (1, 2);
INSERT INTO categoria_libro(libro, categoria) VALUES (2, 3);
INSERT INTO categoria_libro(libro, categoria) VALUES (3, 4);
INSERT INTO categoria_libro(libro, categoria) VALUES (4, 5);
INSERT INTO categoria_libro(libro, categoria) VALUES (5, 6);
INSERT INTO categoria_libro(libro, categoria) VALUES (6, 7);
INSERT INTO categoria_libro(libro, categoria) VALUES (7, 8);
INSERT INTO categoria_libro(libro, categoria) VALUES (8, 9);
INSERT INTO categoria_libro(libro, categoria) VALUES (9, 10);
INSERT INTO categoria_libro(libro, categoria) VALUES (10, 11);
INSERT INTO categoria_libro(libro, categoria) VALUES (11, 12);
INSERT INTO categoria_libro(libro, categoria) VALUES (12, 13);
INSERT INTO categoria_libro(libro, categoria) VALUES (13, 14);
INSERT INTO categoria_libro(libro, categoria) VALUES (14, 15);
INSERT INTO categoria_libro(libro, categoria) VALUES (15, 16);
INSERT INTO categoria_libro(libro, categoria) VALUES (16, 17);
INSERT INTO categoria_libro(libro, categoria) VALUES (17, 18);
INSERT INTO categoria_libro(libro, categoria) VALUES (18, 19);
INSERT INTO categoria_libro(libro, categoria) VALUES (19, 20);
INSERT INTO categoria_libro(libro, categoria) VALUES (20, 1);
INSERT INTO categoria_libro(libro, categoria) VALUES (1, 3);
INSERT INTO categoria_libro(libro, categoria) VALUES (2, 4);
INSERT INTO categoria_libro(libro, categoria) VALUES (3, 5);
INSERT INTO categoria_libro(libro, categoria) VALUES (4, 6);
INSERT INTO categoria_libro(libro, categoria) VALUES (5, 7);
INSERT INTO categoria_libro(libro, categoria) VALUES (6, 8);
INSERT INTO categoria_libro(libro, categoria) VALUES (7, 9);
INSERT INTO categoria_libro(libro, categoria) VALUES (8, 10);
INSERT INTO categoria_libro(libro, categoria) VALUES (9, 11);
INSERT INTO categoria_libro(libro, categoria) VALUES (10, 12);
INSERT INTO categoria_libro(libro, categoria) VALUES (11, 13);
INSERT INTO categoria_libro(libro, categoria) VALUES (12, 14);
INSERT INTO categoria_libro(libro, categoria) VALUES (13, 15);
INSERT INTO categoria_libro(libro, categoria) VALUES (14, 16);
INSERT INTO categoria_libro(libro, categoria) VALUES (15, 17);
INSERT INTO categoria_libro(libro, categoria) VALUES (16, 18);
INSERT INTO categoria_libro(libro, categoria) VALUES (17, 19);
INSERT INTO categoria_libro(libro, categoria) VALUES (18, 20);
INSERT INTO categoria_libro(libro, categoria) VALUES (19, 1);
INSERT INTO categoria_libro(libro, categoria) VALUES (20, 2);

